"""Add missing columns to FloorPlanProject

Revision ID: f9385165250b
Revises: 
Create Date: 2026-04-16 13:02:41.897252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f9385165250b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_estimates_id'), table_name='estimates')
    op.drop_table('estimates')
    op.alter_column('floorplan_3d_models', 'project_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='UNIQUE - one project can only have one 3D model record',
               existing_nullable=False)
    op.alter_column('floorplan_3d_models', 'generation_method',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='How the model was created: rule_based (extrusion), ml_extrusion, hybrid, etc.',
               existing_nullable=False,
               existing_server_default=sa.text("'rule_based'::character varying"))
    op.drop_index(op.f('idx_3d_generation_method'), table_name='floorplan_3d_models')
    op.drop_index(op.f('idx_3d_model_code'), table_name='floorplan_3d_models', postgresql_where='(model_code IS NOT NULL)')
    op.drop_index(op.f('idx_3d_project'), table_name='floorplan_3d_models')
    op.drop_index(op.f('idx_3d_status'), table_name='floorplan_3d_models')
    op.create_index(op.f('ix_floorplan_3d_models_id'), 'floorplan_3d_models', ['id'], unique=False)
    op.drop_table_comment(
        'floorplan_3d_models',
        existing_comment='3D model metadata and file references. One project can have one 3D model (one-to-one relationship).',
        schema=None
    )
    op.alter_column('floorplan_costs', 'category',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Cost category: flooring, painting, electrical, plumbing, etc.',
               existing_nullable=False)
    op.alter_column('floorplan_costs', 'grand_total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Final total including tax and markup',
               existing_nullable=True)
    op.drop_index(op.f('idx_costs_applies_to'), table_name='floorplan_costs')
    op.drop_index(op.f('idx_costs_approved'), table_name='floorplan_costs', postgresql_where='(is_approved = true)')
    op.drop_index(op.f('idx_costs_category'), table_name='floorplan_costs')
    op.drop_index(op.f('idx_costs_project'), table_name='floorplan_costs')
    op.drop_index(op.f('idx_costs_room'), table_name='floorplan_costs')
    op.create_index(op.f('ix_floorplan_costs_id'), 'floorplan_costs', ['id'], unique=False)
    op.drop_table_comment(
        'floorplan_costs',
        existing_comment='Detailed cost breakdown for projects. Line-item level costing with supplier information.',
        schema=None
    )
    op.alter_column('floorplan_elevation_views', 'view_type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Type of view: side, front, back, cross_section, elevation, etc.',
               existing_nullable=False)
    op.alter_column('floorplan_elevation_views', 'extracted_height_ft',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Height extracted from image analysis. Used for 3D model generation.',
               existing_nullable=True)
    op.drop_index(op.f('idx_elevation_direction'), table_name='floorplan_elevation_views')
    op.drop_index(op.f('idx_elevation_project'), table_name='floorplan_elevation_views')
    op.drop_index(op.f('idx_elevation_status'), table_name='floorplan_elevation_views')
    op.drop_index(op.f('idx_elevation_type'), table_name='floorplan_elevation_views')
    op.drop_index(op.f('idx_elevation_uploaded'), table_name='floorplan_elevation_views')
    op.create_index(op.f('ix_floorplan_elevation_views_id'), 'floorplan_elevation_views', ['id'], unique=False)
    op.drop_table_comment(
        'floorplan_elevation_views',
        existing_comment='Side views, cross-sections, and elevations for height extraction and 3D validation.',
        schema=None
    )
    op.alter_column('floorplan_openings', 'opening_type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Type: door, window, sliding_door, french_door, or skylight',
               existing_nullable=False)
    op.drop_index(op.f('idx_openings_exterior'), table_name='floorplan_openings', postgresql_where='(is_exterior = true)')
    op.drop_index(op.f('idx_openings_project'), table_name='floorplan_openings')
    op.drop_index(op.f('idx_openings_room'), table_name='floorplan_openings')
    op.drop_index(op.f('idx_openings_type'), table_name='floorplan_openings')
    op.create_index(op.f('ix_floorplan_openings_id'), 'floorplan_openings', ['id'], unique=False)
    op.create_foreign_key(None, 'floorplan_openings', 'floorplan_walls', ['wall_id'], ['id'], ondelete='SET NULL')
    op.drop_table_comment(
        'floorplan_openings',
        existing_comment='Doors, windows, and other openings. Used for 3D reconstruction and cost estimation.',
        schema=None
    )
    op.add_column('floorplan_projects', sa.Column('description', sa.Text(), nullable=True))
    op.alter_column('floorplan_projects', 'project_code',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Unique identifier like PROJ-2024-00001. Auto-generated on insert.',
               existing_nullable=True)
    op.alter_column('floorplan_projects', 'rooms_json',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Complete room data in JSON. Source of truth for reports. Synchronized with floorplan_rooms table.',
               existing_nullable=True)
    op.alter_column('floorplan_projects', 'source_type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Source: ai_upload (analyzed from image), manual_form (user filled form), hybrid (AI + manual edits), import (CAD/PDF)',
               existing_nullable=True,
               existing_server_default=sa.text("'ai_upload'::character varying"))
    op.alter_column('floorplan_projects', 'has_floor_plan_image',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='TRUE if project has uploaded floor plan image. FALSE for manual form entries.',
               existing_nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('floorplan_projects', 'has_geometry_data',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='TRUE if rooms/walls have coordinate data. FALSE for manual form entries without geometry.',
               existing_nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('floorplan_projects', 'estimated_cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Total project cost. Calculated from floorplan_costs table.',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('idx_projects_ai'), table_name='floorplan_projects', postgresql_where="((source_type)::text = 'ai_upload'::text)")
    op.drop_index(op.f('idx_projects_code'), table_name='floorplan_projects')
    op.drop_index(op.f('idx_projects_created'), table_name='floorplan_projects')
    op.drop_index(op.f('idx_projects_manual'), table_name='floorplan_projects', postgresql_where="((source_type)::text = 'manual_form'::text)")
    op.drop_index(op.f('idx_projects_source_type'), table_name='floorplan_projects')
    op.drop_index(op.f('idx_projects_status'), table_name='floorplan_projects')
    op.drop_index(op.f('idx_projects_user'), table_name='floorplan_projects', postgresql_where='(is_deleted = false)')
    op.create_index(op.f('ix_floorplan_projects_id'), 'floorplan_projects', ['id'], unique=False)
    op.drop_table_comment(
        'floorplan_projects',
        existing_comment='Master table for floor plan projects. Contains summary data and JSON snapshots for fast access.',
        schema=None
    )
    op.alter_column('floorplan_rooms', 'room_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Type of room: bedroom, kitchen, bathroom, etc.',
               existing_nullable=False)
    op.alter_column('floorplan_rooms', 'area_sqft',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Room area in square feet. Calculated from bounds using scale_px_per_foot.',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('floorplan_rooms', 'has_geometry',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='TRUE if room has coordinate geometry (x_min, y_min, etc.). FALSE for manual form entries.',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('idx_rooms_area'), table_name='floorplan_rooms')
    op.drop_index(op.f('idx_rooms_floor'), table_name='floorplan_rooms')
    op.drop_index(op.f('idx_rooms_project'), table_name='floorplan_rooms')
    op.drop_index(op.f('idx_rooms_type'), table_name='floorplan_rooms')
    op.drop_index(op.f('idx_rooms_wet'), table_name='floorplan_rooms', postgresql_where='(is_wet_room = true)')
    op.create_index(op.f('ix_floorplan_rooms_id'), 'floorplan_rooms', ['id'], unique=False)
    op.drop_table_comment(
        'floorplan_rooms',
        existing_comment='Individual rooms extracted from floor plans. Normalized for querying. Synchronized with floorplan_projects.rooms_json.',
        schema=None
    )
    op.alter_column('floorplan_walls', 'wall_type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Type: exterior, interior, load_bearing, partition, or curtain',
               existing_nullable=False,
               existing_server_default=sa.text("'interior'::character varying"))
    op.alter_column('floorplan_walls', 'room_id_left',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Room on left side of wall (can be NULL for exterior walls)',
               existing_nullable=True)
    op.alter_column('floorplan_walls', 'has_geometry',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='TRUE if wall has coordinate geometry. FALSE if wall count only (manual form).',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('idx_walls_project'), table_name='floorplan_walls')
    op.drop_index(op.f('idx_walls_room_left'), table_name='floorplan_walls')
    op.drop_index(op.f('idx_walls_room_right'), table_name='floorplan_walls')
    op.drop_index(op.f('idx_walls_structural'), table_name='floorplan_walls', postgresql_where='(is_structural = true)')
    op.drop_index(op.f('idx_walls_type'), table_name='floorplan_walls')
    op.create_index(op.f('ix_floorplan_walls_id'), 'floorplan_walls', ['id'], unique=False)
    op.drop_table_comment(
        'floorplan_walls',
        existing_comment='Wall segments for 3D reconstruction. Auto-generated from room boundaries or manually defined.',
        schema=None
    )
    op.drop_index(op.f('idx_users_active'), table_name='users', postgresql_where='(is_active = true)')
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_index(op.f('idx_users_username'), table_name='users')
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_table_comment(
        'users',
        existing_comment='Application users who own floor plan projects',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'users',
        'Application users who own floor plan projects',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_users_username'), 'users', ['username'], unique=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('idx_users_active'), 'users', ['is_active'], unique=False, postgresql_where='(is_active = true)')
    op.create_table_comment(
        'floorplan_walls',
        'Wall segments for 3D reconstruction. Auto-generated from room boundaries or manually defined.',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_floorplan_walls_id'), table_name='floorplan_walls')
    op.create_index(op.f('idx_walls_type'), 'floorplan_walls', ['wall_type'], unique=False)
    op.create_index(op.f('idx_walls_structural'), 'floorplan_walls', ['is_structural'], unique=False, postgresql_where='(is_structural = true)')
    op.create_index(op.f('idx_walls_room_right'), 'floorplan_walls', ['room_id_right'], unique=False)
    op.create_index(op.f('idx_walls_room_left'), 'floorplan_walls', ['room_id_left'], unique=False)
    op.create_index(op.f('idx_walls_project'), 'floorplan_walls', ['project_id'], unique=False)
    op.alter_column('floorplan_walls', 'has_geometry',
               existing_type=sa.BOOLEAN(),
               comment='TRUE if wall has coordinate geometry. FALSE if wall count only (manual form).',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('floorplan_walls', 'room_id_left',
               existing_type=sa.INTEGER(),
               comment='Room on left side of wall (can be NULL for exterior walls)',
               existing_nullable=True)
    op.alter_column('floorplan_walls', 'wall_type',
               existing_type=sa.VARCHAR(length=20),
               comment='Type: exterior, interior, load_bearing, partition, or curtain',
               existing_nullable=False,
               existing_server_default=sa.text("'interior'::character varying"))
    op.create_table_comment(
        'floorplan_rooms',
        'Individual rooms extracted from floor plans. Normalized for querying. Synchronized with floorplan_projects.rooms_json.',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_floorplan_rooms_id'), table_name='floorplan_rooms')
    op.create_index(op.f('idx_rooms_wet'), 'floorplan_rooms', ['is_wet_room'], unique=False, postgresql_where='(is_wet_room = true)')
    op.create_index(op.f('idx_rooms_type'), 'floorplan_rooms', ['room_type'], unique=False)
    op.create_index(op.f('idx_rooms_project'), 'floorplan_rooms', ['project_id'], unique=False)
    op.create_index(op.f('idx_rooms_floor'), 'floorplan_rooms', ['floor_level'], unique=False)
    op.create_index(op.f('idx_rooms_area'), 'floorplan_rooms', ['area_sqft'], unique=False)
    op.alter_column('floorplan_rooms', 'has_geometry',
               existing_type=sa.BOOLEAN(),
               comment='TRUE if room has coordinate geometry (x_min, y_min, etc.). FALSE for manual form entries.',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('floorplan_rooms', 'area_sqft',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Room area in square feet. Calculated from bounds using scale_px_per_foot.',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('floorplan_rooms', 'room_type',
               existing_type=sa.VARCHAR(length=50),
               comment='Type of room: bedroom, kitchen, bathroom, etc.',
               existing_nullable=False)
    op.create_table_comment(
        'floorplan_projects',
        'Master table for floor plan projects. Contains summary data and JSON snapshots for fast access.',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_floorplan_projects_id'), table_name='floorplan_projects')
    op.create_index(op.f('idx_projects_user'), 'floorplan_projects', ['user_id'], unique=False, postgresql_where='(is_deleted = false)')
    op.create_index(op.f('idx_projects_status'), 'floorplan_projects', ['status'], unique=False)
    op.create_index(op.f('idx_projects_source_type'), 'floorplan_projects', ['source_type'], unique=False)
    op.create_index(op.f('idx_projects_manual'), 'floorplan_projects', ['source_type'], unique=False, postgresql_where="((source_type)::text = 'manual_form'::text)")
    op.create_index(op.f('idx_projects_created'), 'floorplan_projects', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_projects_code'), 'floorplan_projects', ['project_code'], unique=True)
    op.create_index(op.f('idx_projects_ai'), 'floorplan_projects', ['source_type'], unique=False, postgresql_where="((source_type)::text = 'ai_upload'::text)")
    op.alter_column('floorplan_projects', 'estimated_cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Total project cost. Calculated from floorplan_costs table.',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('floorplan_projects', 'has_geometry_data',
               existing_type=sa.BOOLEAN(),
               comment='TRUE if rooms/walls have coordinate data. FALSE for manual form entries without geometry.',
               existing_nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('floorplan_projects', 'has_floor_plan_image',
               existing_type=sa.BOOLEAN(),
               comment='TRUE if project has uploaded floor plan image. FALSE for manual form entries.',
               existing_nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('floorplan_projects', 'source_type',
               existing_type=sa.VARCHAR(length=20),
               comment='Source: ai_upload (analyzed from image), manual_form (user filled form), hybrid (AI + manual edits), import (CAD/PDF)',
               existing_nullable=True,
               existing_server_default=sa.text("'ai_upload'::character varying"))
    op.alter_column('floorplan_projects', 'rooms_json',
               existing_type=sa.TEXT(),
               comment='Complete room data in JSON. Source of truth for reports. Synchronized with floorplan_rooms table.',
               existing_nullable=True)
    op.alter_column('floorplan_projects', 'project_code',
               existing_type=sa.VARCHAR(length=50),
               comment='Unique identifier like PROJ-2024-00001. Auto-generated on insert.',
               existing_nullable=True)
    op.drop_column('floorplan_projects', 'description')
    op.create_table_comment(
        'floorplan_openings',
        'Doors, windows, and other openings. Used for 3D reconstruction and cost estimation.',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'floorplan_openings', type_='foreignkey')
    op.drop_index(op.f('ix_floorplan_openings_id'), table_name='floorplan_openings')
    op.create_index(op.f('idx_openings_type'), 'floorplan_openings', ['opening_type'], unique=False)
    op.create_index(op.f('idx_openings_room'), 'floorplan_openings', ['room_id'], unique=False)
    op.create_index(op.f('idx_openings_project'), 'floorplan_openings', ['project_id'], unique=False)
    op.create_index(op.f('idx_openings_exterior'), 'floorplan_openings', ['is_exterior'], unique=False, postgresql_where='(is_exterior = true)')
    op.alter_column('floorplan_openings', 'opening_type',
               existing_type=sa.VARCHAR(length=20),
               comment='Type: door, window, sliding_door, french_door, or skylight',
               existing_nullable=False)
    op.create_table_comment(
        'floorplan_elevation_views',
        'Side views, cross-sections, and elevations for height extraction and 3D validation.',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_floorplan_elevation_views_id'), table_name='floorplan_elevation_views')
    op.create_index(op.f('idx_elevation_uploaded'), 'floorplan_elevation_views', [sa.literal_column('uploaded_at DESC')], unique=False)
    op.create_index(op.f('idx_elevation_type'), 'floorplan_elevation_views', ['view_type'], unique=False)
    op.create_index(op.f('idx_elevation_status'), 'floorplan_elevation_views', ['processing_status'], unique=False)
    op.create_index(op.f('idx_elevation_project'), 'floorplan_elevation_views', ['project_id'], unique=False)
    op.create_index(op.f('idx_elevation_direction'), 'floorplan_elevation_views', ['view_direction'], unique=False)
    op.alter_column('floorplan_elevation_views', 'extracted_height_ft',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Height extracted from image analysis. Used for 3D model generation.',
               existing_nullable=True)
    op.alter_column('floorplan_elevation_views', 'view_type',
               existing_type=sa.VARCHAR(length=20),
               comment='Type of view: side, front, back, cross_section, elevation, etc.',
               existing_nullable=False)
    op.create_table_comment(
        'floorplan_costs',
        'Detailed cost breakdown for projects. Line-item level costing with supplier information.',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_floorplan_costs_id'), table_name='floorplan_costs')
    op.create_index(op.f('idx_costs_room'), 'floorplan_costs', ['room_id'], unique=False)
    op.create_index(op.f('idx_costs_project'), 'floorplan_costs', ['project_id'], unique=False)
    op.create_index(op.f('idx_costs_category'), 'floorplan_costs', ['category'], unique=False)
    op.create_index(op.f('idx_costs_approved'), 'floorplan_costs', ['is_approved'], unique=False, postgresql_where='(is_approved = true)')
    op.create_index(op.f('idx_costs_applies_to'), 'floorplan_costs', ['applies_to'], unique=False)
    op.alter_column('floorplan_costs', 'grand_total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Final total including tax and markup',
               existing_nullable=True)
    op.alter_column('floorplan_costs', 'category',
               existing_type=sa.VARCHAR(length=50),
               comment='Cost category: flooring, painting, electrical, plumbing, etc.',
               existing_nullable=False)
    op.create_table_comment(
        'floorplan_3d_models',
        '3D model metadata and file references. One project can have one 3D model (one-to-one relationship).',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_floorplan_3d_models_id'), table_name='floorplan_3d_models')
    op.create_index(op.f('idx_3d_status'), 'floorplan_3d_models', ['processing_status'], unique=False)
    op.create_index(op.f('idx_3d_project'), 'floorplan_3d_models', ['project_id'], unique=True)
    op.create_index(op.f('idx_3d_model_code'), 'floorplan_3d_models', ['model_code'], unique=True, postgresql_where='(model_code IS NOT NULL)')
    op.create_index(op.f('idx_3d_generation_method'), 'floorplan_3d_models', ['generation_method'], unique=False)
    op.alter_column('floorplan_3d_models', 'generation_method',
               existing_type=sa.VARCHAR(length=50),
               comment='How the model was created: rule_based (extrusion), ml_extrusion, hybrid, etc.',
               existing_nullable=False,
               existing_server_default=sa.text("'rule_based'::character varying"))
    op.alter_column('floorplan_3d_models', 'project_id',
               existing_type=sa.INTEGER(),
               comment='UNIQUE - one project can only have one 3D model record',
               existing_nullable=False)
    op.create_table('estimates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('area_sqft', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('floors', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('wastage_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('mix_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('total_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('estimates_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('estimates_pkey'))
    )
    op.create_index(op.f('ix_estimates_id'), 'estimates', ['id'], unique=False)
    # ### end Alembic commands ###
